# **Eigenvalues and eigenvectors**

* Eigenvalues and eigenvectors are
important in many applications.

* Reproduction rate of an infectious
disease in population is determined by
the largest eigenvalue of a matrix.

* Reaction rate of a chemical or
nuclear system is often determined
by the largest eigenvalue of a matrix.

# **Definition:**

Given a square matrix $A \in \mathbb{R}^{n \times n}$, an eigenvalue-eigenvector pair $(\lambda,\textbf{x})$ for a matrix $A$ is a scalar $\lambda$ and vector $\textbf{x} \neq 0$ such that,
$$A \textbf{x} = \lambda \textbf{x}.$$

* Eigenvectors are not unique.

* Eigenvectors are generally normalized to have magnitude of 1 and first nonzero
component to be positive.

* An eigenvector cannot be the zero vector.

Since $A \textbf{x} = \lambda \textbf{x}$, then $\textbf{x}$ is a solution vector to the homogeneous sytem,
$$(A- \lambda I) \textbf{x} = 0$$

Since the above homogeneous system has nonzero solution, the coefficient matrix must be singular. That is, the inverse does not exist.

In other words,
$$ \text{det}(A- \lambda I) = 0.$$

This is known as the characteristic polynomial for matrix $A$ whose roots are the eigenvalues.

### **Exercise:**
Determine the eigenvalues of the matrix
$$A =
\begin{pmatrix}
2&1\\
1&2
\end{pmatrix}
$$

### **Exercise:**
For every eigenvalue obtained in the previous example find an eigenvector for the matrix $A$.

# **The Power Method**

* For large matrices finding all eigenvalues can be hard and expensive.

* Finding the largest eigenvalue is possible efficiently and accurately.​

* Often, knowing the largest eigenvalue is good enough.

The Power Method is one of the iterative algorithms to compute the dominant eigenvalue (the one with largest magnitude).

* Assume $A$ has eigenvalues satisfying $|\lambda_1| \geq |\lambda_2| \geq \cdots \geq |\lambda_n|$

* Let $\textbf{y}_1,\textbf{y}_2,\cdots,\textbf{y}_n$ be corresponding linearly independent eigenvectors.

* Any $\textbf{x} \in \mathbb{R}^n$ is a linear combination of the eigenvectors,
$$\textbf{x} = \alpha_1\textbf{y}_1+\alpha_2\textbf{y}_2+\cdots+\alpha_n\textbf{y}_n$$

* Hence,
$$
\begin{align*}
A\textbf{x} &= \alpha_1 A \textbf{y}_1+\alpha_2 A \textbf{y}_2+\cdots+\alpha_n A \textbf{y}_n &= \alpha_1 \lambda_1 \textbf{y}_1+\alpha_2 \lambda_2 \textbf{y}_2+\cdots+\alpha_n \lambda_n \textbf{y}_n\\
A^2\textbf{x} &= \alpha_1 A^2 \textbf{y}_1+\alpha_2 A^2 \textbf{y}_2+\cdots+\alpha_n A^2 \textbf{y}_n &= \alpha_1 \lambda_1^2 \textbf{y}_1+\alpha_2 \lambda_2^2 \textbf{y}_2+\cdots+\alpha_n \lambda_n^2 \textbf{y}_n\\
& \vdots & \\
A^m\textbf{x} &= \alpha_1 A^m \textbf{y}_1+\alpha_2 A^m \textbf{y}_2+\cdots+\alpha_n A^m \textbf{y}_n &= \alpha_1 \lambda_1^m \textbf{y}_1+\alpha_2 \lambda_2^m \textbf{y}_2+\cdots+\alpha_n \lambda_n^m \textbf{y}_n
\end{align*}
$$

* For $m$ large enough, $A^m \textbf{x} \approx \alpha_1 \lambda_1^m \textbf{y}_1$.
    
* Using this approximation
$$A A^m \textbf{x} = A^{m+1} \textbf{x} =  \alpha_1 \lambda_1^{m+1} \textbf{y}_1 = \lambda_1 \alpha_1 \lambda_1^{m} \textbf{y}_1 = \lambda_1 A^m \textbf{x}.$$

* That is $A^m \textbf{x}$ is an eigenvector of $A$.


### **The power method algorithm:**

Choose a nonzero vector $\textbf{x}_0$<br>
for $k = 0,1,2, \cdots$<br>
$\;\;\;\;\;\;\;\textbf{y}_{k+1} = A \textbf{x}_k$<br>
$\;\;\;\;\;\;\; \textbf{x}_{k+1} = \frac{\textbf{y}_{k+1}}{\|\textbf{y}_{k+1}\|}$<br>
end<br>
return eigenvector $\textbf{x}_{k+1}$ and eigenvalue $\frac{\textbf{x}_k^T \cdot A\textbf{x}_k}{\textbf{x}_k^T \cdot \textbf{x}_k}$

### **Note:**
At every iteration we normalize the eigenvector:
$$\textbf{x}_{k+1}= \frac{A\textbf{x}_k}{\|A\textbf{x}_k\|}$$
After enough iterations, from the fact that $\lambda_1 \textbf{x}_k=  A\textbf{x}_k$ we recover the eigenvalue as:
$$\frac{\textbf{x}_k^T \cdot A\textbf{x}_k}{\textbf{x}_k^T \cdot \textbf{x}_k}$$



### **Exercise:**
Starting with initial vector $\begin{pmatrix} 1\\0 \end{pmatrix}$, approximate the largest eigenvalue of the matrix

$$
A =
\begin{pmatrix}
2&1\\ 1&2
\end{pmatrix}
$$

In [90]:
# @title
import numpy as np
A = np.array([[2,1],[1,2]])
x = np.array([1,0])

In [91]:
# @title
for i in range(100):
    y = np.matmul(A,x)
    x = y/np.sqrt(np.dot(y,y))
print(x)

[0.70710678 0.70710678]


In [92]:
# @title
# Eigenvalue
eig = np.matmul(x,np.matmul(A,x))/np.matmul(x,x)
print(eig)

3.0000000000000004


### **Note:**
* If $|\lambda_1| \gg |\lambda_2|$ then power method converges really fast.
* How can we find the smallest eigenvalue of a matrix $A$?

    If $\lambda$ is the largest eigenvalue of $A^{-1}$ then $\frac{1}{\lambda}$ is the smallest eigenvalue of $A$.


### **Exercise:**
Use the power method to obtain the eigenvalue of the smallest magnitude of the above matrix.

# **Population Dynamics**

* Consider a population system of animals (say guinea pigs) with constant birth and death rates.
* How does the population change from year to year?
* We can place each individual from the population in one of the following groups,
$$
\begin{align}
P_1, \hspace{5mm} & age \leq 1\\
P_2, \hspace{5mm} & 1 \leq age \leq 2\\
P_3, \hspace{5mm} & 2 \leq age \leq 3\\
P_4, \hspace{5mm} & age \geq 3
\end{align}
$$
    * Birth rates : $b_1,b_2,b_3,b_4$ and
    * Death rates : $d_1, d_2, d_3, d_4$ for each group respectively.
    
* Let $P_j^{(k)}$ be the population of the $j$-th group for the $k$-th year.
* Hence we obtain the following system for the $(n+1)$-th year,
    
$$
\begin{align}
P_1^{(n+1)} &= b_1 P_1^{(n)} + b_2 P_2^{(n)} + b_3 P_3^{(n)} + b_4 P_4^{(n)}\\
P_2^{(n+1)} &= (1-d_1) P_1^{(n)}\\
P_3^{(n+1)} &= (1-d_2) P_2^{(n)}\\
P_4^{(n+1)} &= (1-d_3) P_3^{(n)} + (1-d_4) P_4^{(n)}\\
\end{align}
$$


* That is,
$$
\begin{align*}
\begin{pmatrix}
P_1^{(n+1)}\\
P_2^{(n+1)}\\
P_3^{(n+1)}\\
P_4^{(n+1)}
\end{pmatrix} &=
\begin{pmatrix}
b_1 & b_2 & b_3 & b_4\\
(1-d_1) & 0 & 0 & 0\\
0&(1-d_2)&0&0\\
0&0&(1-d_3)&(1-d_4)
\end{pmatrix} \cdot
\begin{pmatrix}
P_1^{(n)}\\
P_2^{(n)}\\
P_3^{(n)}\\
P_4^{(n)}
\end{pmatrix}\\ &=
\begin{pmatrix}
b_1 & b_2 & b_3 & b_4\\
(1-d_1) & 0 & 0 & 0\\
0&(1-d_2)&0&0\\
0&0&(1-d_3)&(1-d_4)
\end{pmatrix}^n
\cdot
\begin{pmatrix}
P_1^{(0)}\\ P_2^{(0)}\\ P_3^{(0)}\\ P_4^{(0)}
\end{pmatrix}
\end{align*}
$$

* Due to repeated multiplication by the same matrix, the above process is the non-normalized power method!

* Hence the population over a long time is driven by the eigenvalue of largest magnitude of the above matrix.

* For this matrix,
    * if the biggest eigenvalue is bigger than 1, the population grows to infinity.
    * if biggest eigenvalue is less than 1, population goes extinct.
    * if the biggest eigenvalue is 1, then the population is stable.

### **Exercise:**
Consider the above population system. Suppose the birth rates are given as $b_1=0.3, b_2=0.3, b_3=0.3, b_4 = 0.1$ and the death rates are given as $d_1 = 0.1, d_2 = 0.2, d_3 = 0.5, \text{ and } d_4 = 0.9.$

* What is the biggest eigenvalue of the resulting matrix?
* What happens to the population size over a long time period?

In [110]:
import numpy as np
A = np.array([[0.3,0.3,0.3,0.1],[0.9, 0,0,0],[0,0.8,0,0],[0,0,0.5,0.1]])
x = np.array([1,0,0,0])

In [111]:
for i in range(1000):
    y = np.matmul(A,x)
    x = y/np.sqrt(np.dot(y,y))
print(x)

[0.57564249 0.56895295 0.49985881 0.30833333]


In [112]:
# Eigenvalue
eig = np.matmul(x,np.matmul(A,x))/np.matmul(x,x)
print(eig)

0.9105818605499872


In [109]:
print(np.linalg.eig(A)[0])

[ 0.91058186+0.j         -0.21350849+0.37902122j -0.21350849-0.37902122j
 -0.08356487+0.j        ]


In [ ]:
# Long term effect
A = np.array([[0.3,0.3,0.3,0.1],[0.9, 0,0,0],[0,0.8,0,0],[0,0,0.5,0.1]])
x = np.array([0.25,0.25,0.25,0.25])

In [113]:
for i in range(1000):
    x = np.matmul(A,x)
print(x)

[1.19990659e-41 1.18596249e-41 1.04193816e-41 6.42710017e-42]


# **Stochastic Matrices**
A square matrix $P$ is stochastic if all of its entries are nonnegative, and the entries of each column sum to $1$.

Each entry $p_{ij}$ in a stochastic matrix represents the probability of moving from state $j$ to state $i$, and satisfies,

$$p_{ij} \geq 0, \;\;\;\; \sum\limits_{i=1}^n p_{ij} = 1, \forall j$$
[That is, each column sums to 1]



### **Steady-state:**
The steady-state distribution or the steady state vector of a stochastic matrix is a vector $\pi$ that satisfies the following:
* $\pi = P \pi.$
* The entries add up to one, i.e.:
$\sum \pi_i = 1.$

### **Exercise:**
Consider the following matrix,
$$
P =
\begin{pmatrix}
0.3 &0.4 &0.5\\
0.3 &0.4 &0.3\\
0.4 &0.2 &0.2
\end{pmatrix}
$$
* Verify that $P$ is a stochastic matrix.
* Starting from the initial state distribution
$$\pi_0 = [1,0,0]^T$$
compute the distribution after two steps, i.e. $\pi_2$
* Find the steady-state distribution $\pi$ such that $\pi = P \pi.$
* Verify numerically that $\pi = P \pi.$
* Find the largest eigen value of $P$.

In [134]:
P = np.array([[0.3, 0.4, 0.5],[0.3 ,0.4 ,0.3],[0.4,0.2,0.2]])
P

array([[0.3, 0.4, 0.5],
       [0.3, 0.4, 0.3],
       [0.4, 0.2, 0.2]])

In [138]:
pi = np.array([1,0,0])

In [139]:
for i in range(1000):
    pi = np.matmul(P,pi)

print(pi)

[0.38888889 0.33333333 0.27777778]


In [141]:
np.matmul(pi,pi)

np.float64(0.3395061728395065)

In [143]:
np.matmul(P,pi)

array([0.38888889, 0.33333333, 0.27777778])

In [147]:
A = np.array([[0.3, 0.4, 0.5],[0.3 ,0.4 ,0.3],[0.4,0.2,0.2]])
A

array([[0.3, 0.4, 0.5],
       [0.3, 0.4, 0.3],
       [0.4, 0.2, 0.2]])

In [148]:
x = np.array([1,0,0])

In [152]:
for i in range(100):
    y = np.matmul(A,x)
    x = y/np.sqrt(np.dot(y,y))
print(x)

[0.66742381 0.57207755 0.47673129]


In [153]:
# Eigenvalue
eig = np.matmul(x,np.matmul(A,x))/np.matmul(x,x)
print(eig)

1.0
